config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :items, only: [:index,:show]

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id                :string          not null, primary key
#  title             :string
#  image_url         :string

class Item < ActiveRecord::Base
  # making own id column act as primary key
  self.primary_key = :id

  #addding has_many associtation to review model
  has_many :reviews

  def counters
    {reviews: self.reviews_count}
  end
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id                :string          not null, primary key
#  content           :string
#  item_id           :string

class Review < ActiveRecord::Base
  # making own id column act as primary key
  self.primary_key = :id

  # adding belongs to association to item model, adding cache to update count of reviews everytime review of an item is added
  belongs_to :item, counter_cache: :reviews_count

  #limiting only 10 reviews
  scope :limited_reviews, lambda {limit(10)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  # GET index
  def index
    if Item.first
      @item_id = Item.first.id
      @item_id = "{\"#{@item_id}\"}"
    end
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show]

  # GET /items
  # returning data only in json format
  def index
    @export_items = Item.order("reviews_count DESC")
    @items = @export_items.page(params[:page]).per(10)
    render json: @items
  end

  # GET /items/1
  # returning data only in json format
  def show
    render json: @item
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    params_length = params[:id].length
    id = params[:id].slice(2, params_length-4)
    @item = Item.find(id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome to Opiyn Backend</h1>

<h2 style="margin-left: 10%">       ....where fun begins</h2>

<h1> Api endpoints : </h1>
<h2> <%= link_to "/items", items_path %></h2>
<h2> Page 2 <%= link_to "/items?page=2", "/items/?page=2"%></h2>
<h2> <%= link_to "/items/{itemId}", item_path(@item_id) %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpiynBackend</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>